---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- name: boshrelease-ci

params:
  router_ip:

  cf_system_domain:
  cf_admin_password:
  cf_admin_username:
  cf_skip_ssl_validation:

run:
  path: boshrelease-ci/ci/tasks/assert-disaster-recovery.sh
