---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- name: boshrelease-ci
- name: etcd
- name: simple-remote-syslog
- name: candidate-release
- name: director-state

outputs:
- name: manifest

params:
  bosh_syslog_host:
  bosh_syslog_port:
  deployment_name:
  docker_image_source: upstream
  docker_image_image: "dingotiles/dingo-postgresql95"
  docker_image_tag: "9.5"
  aws_access_key:
  aws_secret_key:
  region:
  backups_bucket:
  clusterdata_bucket:
  enable_syslog:

run:
  path: boshrelease-ci/ci/tasks/create-manifest.sh
