---
platform: linux
image_resource:
  type: docker-image
  source: {repository: dingotiles/dingo-postgresql-release-pipeline}

inputs:
- name: boshrelease-ci

params:
  broker_host:
  broker_port: 8888

  plan_id: 1545e30e-6dc3-11e5-826a-6c4008a663f0
  service_id: beb5973c-e1b2-11e5-a736-c7c0b526363d

  cf_system_domain:
  cf_admin_password:
  cf_admin_username:
  cf_skip_ssl_validation:

run:
  path: boshrelease-ci/ci/tasks/prepare-disaster-recovery.sh
