meta:
  stemcell: (( param "please provide stemcell name/version" ))

name: (( grab meta.name ))

director_uuid: (( param "please provide director_uuid" ))

networks: (( param "please provide networks" ))

jobs: (( param "please provide jobs" ))

properties: {}

compilation:
  workers: 6
  network: patroni1
  reuse_compilation_vms: true
  cloud_properties: (( param "please provide compilation cloud_properties" ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-120000
  update_watch_time: 20000-120000
  serial: true

resource_pools:
  - name: cell_z1
    network: patroni1
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please provide cloud_properties" ))
  - name: router_z1
    network: router1
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please provide cloud_properties" ))
