---
name: dingo-postgresql-vsphere
director_uuid: f635b1ba-5000-48e1-92c8-19471d20e0e4
releases:
- name: dingo-postgresql
  version: latest
- name: simple-remote-syslog
  version: latest
- name: etcd
  version: latest
compilation:
  reuse_compilation_vms: true
  network: patroni1
  cloud_properties:
    ram: 4096
    disk: 20480
    cpu: 4
  workers: 2
# 10.58.111.54 - 10.58.111.54
instance_groups:
- name: etcd
  instances: 1
  jobs:
  - name: remote-syslog
    release: simple-remote-syslog
  - name: etcd
    release: etcd
  resource_pool: router_z1
  networks: [{name: patroni1, static_ips: [10.58.111.59]}]
  persistent_disk: 10240
  properties:
    etcd:
      peer_require_ssl: false
      require_ssl: false
- name: cell_z1
  instances: 2
  networks: [{name: patroni1, static_ips: [10.58.111.55, 10.58.111.58]}]
  persistent_disk: 10240
  properties:
    release_version: (( grab meta.release_version ))
  resource_pool: cell_z1
  jobs:
  - name: remote-syslog
    release: simple-remote-syslog
  - name: docker
    release: dingo-postgresql
  - name: upstream-images
    release: dingo-postgresql
    properties:
      upstream_images:
        tag: "edge"
  - name: registrator
    release: dingo-postgresql
  - name: container-env-vars
    release: dingo-postgresql
  - name: cf-containers-broker
    release: dingo-postgresql
    provides:
      cf-containers-broker:
        as: cell_az1
    properties:
      cookie_secret: e7247dae-a252-4393-afa3-2219c1c02efd
      fetch_images: true
      max_containers: 20
      username: containers
      password: containers
      host: cf-containers-broker.10.244.0.34.xip.io
      port: 80
      ssl_enabled: false
      protocol: http
- name: cell_z2
  instances: 2
  networks: [{name: patroni1, static_ips: [10.58.111.56, 10.58.111.60]}]
  persistent_disk: 10240
  properties:
    release_version: (( grab meta.release_version ))
  resource_pool: cell_z2
  jobs:
  - name: remote-syslog
    release: simple-remote-syslog
  - name: docker
    release: dingo-postgresql
  - name: registrator
    release: dingo-postgresql
  - name: upstream-images
    release: dingo-postgresql
    properties:
      upstream_images:
        tag: "edge"
  - name: container-env-vars
    release: dingo-postgresql
  - name: cf-containers-broker
    release: dingo-postgresql
    provides:
      cf-containers-broker:
        as: cell_az2
    properties:
      cookie_secret: e7247dae-a252-4393-afa3-2219c1c02efd
      fetch_images: true
      max_containers: 20
      username: containers
      password: containers
      host: cf-containers-broker.10.244.0.34.xip.io
      port: 80
      ssl_enabled: false
      protocol: http
- name: router
  jobs:
  - name: remote-syslog
    release: simple-remote-syslog
  - name: broker
    release: dingo-postgresql
    consumes:
      cell:
        from: cell_az1
      cell_z2:
        from: cell_az2
    properties:
      username: starkandwayne
      password: starkandwayne
      advertised_hostname: 10.58.111.57
      etcd:
        machines: [10.58.111.59]
      cf:
        api_url: https://api.system.10-58-111-48.sslip.io
        password: A8tb4yRlQ3BmKmc1TQSCgiN7rAQXiQ73PkeoyI1qGTHq8y523kPZWjGyedjal6kx
        skip_ssl_validation: true
        username: admin
      backups:
        clusterdata:
          aws_access_key_id: (( grab meta.backups.aws_access_key ))
          aws_secret_access_key: (( grab meta.backups.aws_secret_key ))
          bucket_name: (( grab meta.backups.clusterdata_bucket ))
          region: (( grab meta.backups.region ))
        database_storage:
          aws_access_key_id: (( grab meta.backups.aws_access_key ))
          aws_secret_access_key: (( grab meta.backups.aws_secret_key ))
          bucket_name: (( grab meta.backups.backups_bucket ))
          region: (( grab meta.backups.region ))
      services:
      - name: 'dingo-postgresql'
        description: 'High-availability cluster of PostgreSQL 9.5'
        id: beb5973c-e1b2-11e5-a736-c7c0b526363d
        bindable: true
        metadata:
          displayName: 'Dingo PostgreSQL'
          longDescription: 'High-availability cluster of PostgreSQL 9.5 with continuous backups'
          providerDisplayName: 'Dingo Tiles'
          documentationUrl: 'https://pg.dingotiles.com'
          supportUrl: 'https://slack.dingotiles.com'
        tags: [postgresql95, postgresql]
        plans:
        - name: 'cluster'
          description: 'High-availability cluster of PostgreSQL with continuous backups'
          id: 1545e30e-6dc3-11e5-826a-6c4008a663f0
          free: true
          metadata:
            displayName: 'Cluster with continuous backups'
          container:
            backend: docker
            image: dingotiles/dingo-postgresql95
            tag: "edge"
            persistent_volumes: [/data]
            environment:
            - (( concat "AWS_ACCESS_KEY_ID=" meta.backups.aws_access_key ))
            - (( concat "AWS_SECRET_ACCESS_KEY=" meta.backups.aws_secret_key ))
            - (( concat "WAL_S3_BUCKET=" meta.backups.backups_bucket ))
            - (( concat "AWS_REGION=" meta.backups.region ))
            - "WALE_BACKUP_THRESHOLD_PERCENTAGE=30"
            - "WALE_BACKUP_THRESHOLD_MEGABYTES=10240"
  - name: router
    release: dingo-postgresql
  - name: dpg-cli
    release: dingo-postgresql
  resource_pool: router_z1
  instances: 1
  networks: [{name: patroni1, static_ips: [10.58.111.57]}]
- name: sanity-test
  instances: 1
  lifecycle: errand
  jobs:
  - name: sanity-test
    release: dingo-postgresql
    properties:
      etcd:
        machines: [10.58.111.59]
  networks: [{name: patroni1}]
  resource_pool: router_z1
networks:
- name: patroni1
  type: manual
  subnets:
  - range: 10.58.111.0/24
    gateway: 10.58.111.1
    dns:
    - 10.58.20.2
    - 10.57.20.2
    static:
    - 10.58.111.54
    - 10.58.111.55
    - 10.58.111.56
    - 10.58.111.57
    - 10.58.111.58
    - 10.58.111.59
    - 10.58.111.60
    reserved:
    - 10.58.111.2-10.58.111.53
    - 10.58.111.65-10.58.111.254
    cloud_properties:
      name: net-10-58-111-0
properties:
  etcd:
    machines: [10.58.111.59]
resource_pools:
- cloud_properties:
    ram: 4096
    disk: 20480
    cpu: 2
  name: cell_z1
  network: patroni1
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest
- name: cell_z2
  cloud_properties:
    ram: 4096
    disk: 20480
    cpu: 2
  network: patroni1
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest
- name: router_z1
  cloud_properties:
    ram: 4096
    disk: 20480
    cpu: 1
  network: patroni1
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: latest
update:
  canaries: 1
  canary_watch_time: 30000-300000
  max_in_flight: 1
  serial: true
  update_watch_time: 30000-300000
